version: '3.9'
services:
  node:
    build: .
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    environment:
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - network
  postgres:
    build: ./db
    restart: always
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - network
volumes:
  db:
networks:
  network: