version: '3'
services:
  node:
    build: .
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    environment:
      PORT: ${PORT}
    networks:
      - network
  postgres:
    build: ./db
    restart: always
    environment:
      PG_PORT: ${PG_PORT}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network
volumes:
  db:
    name: database
networks:
  network:
    name: network